export const TWEETS_LIST_REQUEST = 'TWEETS_LIST_REQUEST';
export const TWEETS_LIST_FETCH = 'TWEETS_LIST_FETCH';
export const TWEETS_LIST_FAIL = 'TWEETS_LIST_FAIL';

export const TWEETS_CONFIG_UPDATE = 'TWEETS_CONFIG_UPDATE';
